### ISSUE TITLE
EMails not sending

### ISSUE THREAD

**Issue by metaxy** [churchio/onebody#485]
The Emails are not going out. The user does not even see a error message.

I am using mailgun.

This is from the production.log
```
I, [2015-05-08T15:50:48.891765 #24]  INFO -- : [ActiveJob] [MessageSendJob] [42d45674-6d82-461c-a029-86b8550cf98a] Performed MessageSendJob from SuckerPunch(email) in 18.39ms
E, [2015-05-08T15:50:48.891866 #24] ERROR -- : Actor crashed!
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
        /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `initialize'
        /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `open'
        /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `tcp_socket'
        /usr/lib/ruby/2.1.0/net/smtp.rb:551:in `block in do_start'
        /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
        /usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
        /usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
        /usr/lib/ruby/2.1.0/net/smtp.rb:550:in `do_start'
        /usr/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
        /home/onebody/.gems/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
        /home/onebody/.gems/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:541:in `deliver_mail'
        /home/onebody/.gems/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
        /home/onebody/.gems/gems/actionmailer-4.2.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
        /var/www/onebody/app/models/message.rb:103:in `send_to_person'
        /var/www/onebody/app/models/message.rb:111:in `block in send_to_group'
        /home/onebody/.gems/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
        /home/onebody/.gems/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
        /var/www/onebody/app/models/message.rb:109:in `send_to_group'
        /var/www/onebody/app/models/message.rb:92:in `send_message'
        /var/www/onebody/app/jobs/message_send_job.rb:7:in `block (2 levels) in perform'
        /var/www/onebody/app/models/site.rb:28:in `with_current'
        /var/www/onebody/app/jobs/message_send_job.rb:6:in `block in perform'
        /home/onebody/.gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
        /var/www/onebody/app/jobs/message_send_job.rb:6:in `block in perform'
        /home/onebody/.gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
        /var/www/onebody/app/jobs/message_send_job.rb:5:in `perform'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/execution.rb:32:in `block in perform_now'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:62:in `call'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:62:in `run_in_transaction'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:48:in `perform'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:62:in `run_in_transaction'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:48:in `perform'
        /home/onebody/.gems/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `instance_exec'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `block in simple'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `call'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `block in tag_logger'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `tag_logger'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `instance_exec'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `block in simple'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_perform_callbacks'
        /home/onebody/.gems/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/execution.rb:31:in `perform_now'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/execution.rb:21:in `execute'
        /home/onebody/.gems/gems/activejob-4.2.1/lib/active_job/queue_adapters/sucker_punch_adapter.rb:35:in `perform'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /home/onebody/.gems/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by seven1m** [comment]
You didn't configure your email.yml file correctly. Sorry I'm out right now but I can help a bit later.

**Comment by metaxy** [comment]
You were right. I forget to create the config/email.yml file.

But it also had to add in the Dockerfile the following line:
```
ADD config/email.yml /var/www/onebody/config/email.yml
```

Since without it, email.yml was not included in the instance.

**Comment by seven1m** [comment]
Ahh good catch. Do you want to submit that change as a PR so it can help others?
