### ISSUE TITLE
UTF-8 causes Messages to fail

### ISSUE THREAD

**Issue by metaxy** [churchio/onebody#547]
When sending an Message to a group with the character "😃" it will fail.

```
E, [2015-09-21T14:08:36.897313 #22] ERROR -- : Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x83\x0D\x0A...' for column 'body' at row 1: INSERT INTO `messages` (`site_id`, `group_id`, `subject`, `body`, `person_id`, `created_at`, `updated_at`, `code`) VALUES (1, 6, 'snip😃 snip', 29, '2015-09-21 14:08:36', '2015-09-21 14:08:36', 183697)
I, [2015-09-21T14:08:36.897718 #22]  INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.6ms)
F, [2015-09-21T14:08:36.898903 #22] FATAL -- :
ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x83\x0D\x0A...' for column 'body' at row 1: INSERT INTO `messages` (`site_id`, `group_id`, `subject`, `body`, `person_id`, `created_at`, `updated_at`, `code`) VALUES (1, 6, 'title', 'snip😃 snip', 29, '2015-09-21 14:08:36', '2015-09-21 14:08:36', 183697)):
  app/models/message.rb:258:in `create_with_attachments'
  app/controllers/messages_controller.rb:89:in `send_message'
  app/controllers/messages_controller.rb:69:in `create_group_message'
  app/controllers/messages_controller.rb:30:in `create'
```

**Comment by seven1m** [comment]
Yeah I noticed this recently too. :frowning: 

We need to either set the message subject and body columns to utf8mb4 or strip 4-byte chars from messages.

**Comment by seven1m** [comment]
This will be fixed in the next release.
