### ISSUE TITLE
Installing on Debian throws: NameError: uninitialized constant OmniAuth

### ISSUE THREAD

**Issue by cmivxx** [churchio/onebody#593]
So, doing a full install on Debian and got all the way down to:

`RAILS_ENV=production bundle exec rake db:migrate db:seed`

When it barf's and dumps out the following (added --trace for more info):

```
$ RAILS_ENV=production bundle exec rake db:migrate db:seed --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant OmniAuth
/var/www/my-necc/wwwroot/config/initializers/omniauth.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
/var/www/my-necc/wwwroot/config/environment.rb:7:in `<top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```

Everything else passed up until this point.

Any ideas how to proceed?

**Comment by cmivxx** [comment]
I hate to do this, but "BUMP"?

**Comment by seven1m** [comment]
@cmivxx when you run `bundle install`, does the command complete ok? Does it install omniauth-facebook?

**Comment by cmivxx** [comment]
Well, here's the output...   Doesn't look like it's there:

````
bundle install
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using rack 1.6.4
Using mime-types 2.99.1
Using arel 6.0.3
Using thor 0.19.1
Using acts_as_taggable_on_steroids 1.1 from git://github.com/seven1m/acts_as_taggable_on_steroids.git (at cffba03@cffba03)
Using addressable 2.4.0
Using bcrypt 3.1.10
Using coderay 1.1.1
Using debug_inspector 0.0.2
Using sass 3.2.19
Using capistrano-stats 1.1.1
Using net-ssh 3.0.2
Using newrelic_rpm 3.9.9.275
Using hitimes 1.2.3
Using chronic 0.10.2
Using coffee-script-source 1.10.0
Using execjs 2.6.0
Using currencies 0.4.2
Using i18n_data 0.7.0
Using multi_json 1.11.2
Using unf_ext 0.0.7.2
Using netrc 0.11.0
Using docile 1.1.5
Using simplecov-html 0.9.0
Using tins 1.8.2
Using safe_yaml 1.0.4
Using crass 1.0.2
Using curb 0.9.1
Using diff-lcs 1.2.5
Using tilt 1.4.1
Using request_store 1.3.0
Using multipart-post 2.0.0
Using sax-machine 1.3.2
Using ffi 1.9.10
Using formatador 0.2.5
Using geocoder 1.2.14
Using hashie 3.4.3
Using jwt 1.5.1
Using multi_xml 0.5.5
Using rb-fsevent 0.9.7
Using lumberjack 1.0.10
Using nenv 0.3.0
Using shellany 0.0.1
Using method_source 0.8.2
Using slop 3.6.0
Using guard-compat 1.2.1
Using rspec-support 3.1.2
Using highline 1.6.21
Using hike 1.2.3
Using httpclient 2.7.1
Using bundler 1.11.2
Using mini_magick 4.0.4
Using mustache 1.0.2
Using mysql2 0.3.20
Using pusher-signature 0.1.8
Using rubyzip 1.1.7
Using spring 1.2.0
Using terminal-notifier 1.6.3
Using timecop 0.8.0
Using truncate_html 0.9.3
Using watchr 0.7
Using will_paginate 3.0.7
Using tzinfo 1.2.2
Using descendants_tracker 0.0.4
Using nokogiri 1.6.6.4
Using rack-test 0.6.3
Using mail 2.6.3
Using better_errors 2.1.1
Using binding_of_caller 0.7.2
Using bootstrap-sass 3.1.1.1
Using net-scp 1.2.1
Using timers 4.0.4
Using whenever 0.9.4
Using coffee-script 2.4.1
Using uglifier 2.7.2
Using countries 0.11.5
Using unf 0.1.4
Using simplecov 0.9.2
Using term-ansicolor 1.3.2
Using crack 0.4.3
Using haml 4.0.7
Using faraday 0.9.2
Using rb-inotify 0.9.7
Using httparty 0.13.7
Using notiffany 0.0.8
Using pry 0.10.3
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using sprockets 2.12.4
Using pusher 0.14.6
Using zip-zip 0.3
Using spring-commands-rspec 1.0.4
Using will_paginate-bootstrap 1.0.1
Using activesupport 4.2.5.1
Using loofah 2.0.3
Using nokogumbo 1.2.0
Using sshkit 1.8.1
Using celluloid 0.16.0
Using country_select 2.1.0 from git://github.com/stefanpenner/country_select.git (at d3ba0b9@d3ba0b9)
Using domain_name 0.5.20160216
Using webmock 1.20.4
Using oauth2 1.1.0
Using listen 3.0.6
Using pry-rails 0.3.4
Using pry-remote 0.1.8
Using rspec 3.1.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5.1
Using authority 3.0.0
Using climate_control 0.0.3
Using factory_girl 4.5.0
Using shoulda-matchers 2.7.0
Using rails-html-sanitizer 1.0.3
Using feedjira 1.6.0
Using sanitize 3.1.2
Using capistrano 3.3.5
Using sucker_punch 1.3.2
Using http-cookie 1.0.2
Using github_api 0.12.4
Using guard 2.13.0
Using rails-dom-testing 1.0.7
Using activejob 4.2.5.1
Using activerecord 4.2.5.1
Using date_validator 0.7.1
Using cocaine 0.5.8
Using capistrano-bundler 1.1.4
Using capistrano-newrelic 0.0.9
Using rest-client 1.8.0
Using guard-rspec 4.5.2
Using actionview 4.2.5.1
Using acts_as_list 0.6.0
Using paperclip 4.2.4
Using capistrano-rails 1.1.6
Using coveralls 0.7.12
Using actionpack 4.2.5.1
Using actionmailer 4.2.5.1
Using railties 4.2.5.1
Using draper 1.4.0
Using sprockets-rails 2.3.3
Using activerecord-session_store 0.1.2
Using coffee-rails 4.0.1
Using dossier 2.12.2
Using factory_girl_rails 4.5.0
Using font-awesome-rails 4.3.0.0 from git://github.com/bokmann/font-awesome-rails.git (at a67a67e@a67a67e)
Using jquery-rails 4.0.5
Using quiet_assets 1.1.0
Using responders 2.0.2
Using rspec-rails 3.1.0
Using rails 4.2.5.1
Using sass-rails 4.0.5
Using load_and_authorize_resource 0.4.0 from git://github.com/seven1m/load_and_authorize_resource.git (at a77cce9@a77cce9)
Using rails_autolink 1.1.6
Bundle complete! 63 Gemfile dependencies, 162 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
````

**Comment by seven1m** [comment]
Ahh, based on the gem versions, it looks like you checked out the 3.4.0 tag (which is the latest release). That version shouldn't require omniauth and their is no `config/initializers/omniauth.rb` file in that version.

My guess is you have two copies of OneBody -- one with 3.4.0 checked out, and the other with `master` branch checked out.

Make sure you are in the same directory when you run bundle install as what you pointed Apache to.

**Comment by cmivxx** [comment]
I haven't set up apache yet...  And there's only one folder.   This was when I was following the manual install instructions:

https://github.com/churchio/onebody/wiki/Manual-Installation

Step 10:
RAILS_ENV=production bundle exec rake db:migrate db:seed
Watch the output! Don't move on if you see an error on the screen.

And since that failed, I haven't moved on as that RAILS_ENV command isn't completing.  Any idea on how I should keep going?

**Comment by seven1m** [comment]
OK, well seems I was way off base then! Hrrmm....

**Comment by seven1m** [comment]
@cmivxx what is the output of `git status`?

**Comment by cmivxx** [comment]
Here's `git status`:

````
 git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .dockerignore
	modified:   .gitignore
	modified:   .rubocop.yml
	new file:   .ruby-gemset
	modified:   .ruby-version
	modified:   .travis.yml
	modified:   .watchr
	new file:   Dockerfile
	modified:   Gemfile
	modified:   README.md
	modified:   VERSION
	modified:   Vagrantfile
	modified:   app/assets/javascripts/app/admin.js.coffee
	modified:   app/assets/javascripts/app/documents.js.coffee
	modified:   app/assets/javascripts/app/groups.js.coffee
	modified:   app/assets/javascripts/app/search.js.coffee
	modified:   app/assets/javascripts/app/tabs.js.coffee
	modified:   app/assets/javascripts/app/tasks.js.coffee
	modified:   app/assets/javascripts/application.js.coffee
	modified:   app/assets/stylesheets/admin_lte.css
	new file:   app/assets/stylesheets/app/admin.css.scss
	new file:   app/assets/stylesheets/app/avatars.css.scss
	new file:   app/assets/stylesheets/app/boxes.css.scss
	new file:   app/assets/stylesheets/app/breadcrumbs.css.scss
	new file:   app/assets/stylesheets/app/buttons.css.scss
	new file:   app/assets/stylesheets/app/checkin.css.scss
	new file:   app/assets/stylesheets/app/documents.css.scss
	new file:   app/assets/stylesheets/app/families.css.scss
	new file:   app/assets/stylesheets/app/forms.css.scss
	new file:   app/assets/stylesheets/app/friends.css.scss
	new file:   app/assets/stylesheets/app/groups.css.scss
	new file:   app/assets/stylesheets/app/header.css.scss
	new file:   app/assets/stylesheets/app/map.css.scss
	new file:   app/assets/stylesheets/app/menu.css.scss
	new file:   app/assets/stylesheets/app/nav.css.scss
	new file:   app/assets/stylesheets/app/photos.css.scss
	new file:   app/assets/stylesheets/app/pictures.css.scss
	new file:   app/assets/stylesheets/app/privacy.css.scss
	new file:   app/assets/stylesheets/app/profile.css.scss
	new file:   app/assets/stylesheets/app/session.css.scss
	new file:   app/assets/stylesheets/app/share.css.scss
	new file:   app/assets/stylesheets/app/sidebar.css.scss
	new file:   app/assets/stylesheets/app/sparklines.css.scss
	new file:   app/assets/stylesheets/app/tables.css.scss
	new file:   app/assets/stylesheets/app/tabs.css.scss
	new file:   app/assets/stylesheets/app/tags.css.scss
	new file:   app/assets/stylesheets/app/tasks.css.scss
	new file:   app/assets/stylesheets/app/timeline.css.scss
	new file:   app/assets/stylesheets/app/verses.css.scss
	new file:   app/assets/stylesheets/application.css.scss
	new file:   app/assets/stylesheets/checkin-print.css.scss
	new file:   app/assets/stylesheets/checkin-printer.css.scss
	new file:   app/assets/stylesheets/editor.css.scss
	new file:   app/assets/stylesheets/print.css.scss
	modified:   app/authorizers/person_authorizer.rb
	modified:   app/controllers/administration/checkin/times_controller.rb
	modified:   app/controllers/administration/dashboards_controller.rb
	new file:   app/controllers/administration/logos_controller.rb
	modified:   app/controllers/administration/settings_controller.rb
	new file:   app/controllers/administration/syncs_controller.rb
	modified:   app/controllers/application_controller.rb
	modified:   app/controllers/comments_controller.rb
	modified:   app/controllers/documents_controller.rb
	modified:   app/controllers/emails_controller.rb
	modified:   app/controllers/families_controller.rb
	modified:   app/controllers/groups_controller.rb
	modified:   app/controllers/memberships_controller.rb
	modified:   app/controllers/people_controller.rb
	modified:   app/controllers/pictures_controller.rb
	modified:   app/controllers/printable_directories_controller.rb
	modified:   app/controllers/privacies_controller.rb
	modified:   app/controllers/sessions_controller.rb
	modified:   app/controllers/streams_controller.rb
	modified:   app/controllers/tags_controller.rb
	modified:   app/controllers/tasks_controller.rb
	modified:   app/decorators/stream_item_decorator.rb
	new file:   app/helpers/administration/logos_helper.rb
	modified:   app/helpers/administration/settings_helper.rb
	new file:   app/helpers/administration/syncs_helper.rb
	modified:   app/helpers/application_helper.rb
	modified:   app/helpers/families_helper.rb
	new file:   app/helpers/pc_syncs_helper.rb
	modified:   app/helpers/photos_helper.rb
	new file:   app/helpers/syncs_helper.rb
	modified:   app/jobs/stream_item_group_job.rb
	modified:   app/models/admin.rb
	modified:   app/models/album.rb
	modified:   app/models/checkin_time.rb
	modified:   app/models/comparator.rb
	modified:   app/models/concerns/file_image.rb
	modified:   app/models/concerns/geocode.rb
	new file:   app/models/concerns/person/batch.rb
	modified:   app/models/concerns/person/export.rb
	modified:   app/models/concerns/person/friend.rb
	modified:   app/models/concerns/person/import.rb
	modified:   app/models/concerns/person/pdf_gen.rb
	modified:   app/models/concerns/person/relationships.rb
	modified:   app/models/concerns/person/streamable.rb
	modified:   app/models/document.rb
	modified:   app/models/document_folder_group.rb
	new file:   app/models/email.rb
	modified:   app/models/family.rb
	modified:   app/models/group.rb
	modified:   app/models/message.rb
	modified:   app/models/notifier.rb
	modified:   app/models/person.rb
	modified:   app/models/relationship.rb
	modified:   app/models/search.rb
	modified:   app/models/setting.rb
	modified:   app/models/setup.rb
	modified:   app/models/signup.rb
	modified:   app/models/site.rb
	modified:   app/models/stream_item.rb
	new file:   app/models/sync.rb
	new file:   app/models/sync_item.rb
	modified:   app/models/task.rb
	modified:   app/models/updater.rb
	modified:   app/models/verification.rb
	modified:   app/presenters/breadcrumb_presenter.rb
	modified:   app/presenters/stats/attendance_graph_presenter.rb
	modified:   app/reports/group_contact_details_report.rb
	modified:   app/reports/weekly_attendance_report.rb
	modified:   app/views/administration/checkin/groups/update.js.erb
	modified:   app/views/administration/dashboards/show.html.haml
	modified:   app/views/administration/deleted_people/index.html.haml
	new file:   app/views/administration/logos/show.html.erb
	modified:   app/views/administration/settings/index.html.haml
	new file:   app/views/administration/syncs/index.html.haml
	new file:   app/views/administration/syncs/show.html.haml
	modified:   app/views/administration/updates/error.html.haml
	modified:   app/views/albums/_form.haml
	modified:   app/views/checkin/families/update.js.erb
	modified:   app/views/documents/_folder_form.haml
	modified:   app/views/documents/_form.haml
	modified:   app/views/documents/index.html.haml
	modified:   app/views/documents/show.html.haml
	modified:   app/views/dossier/reports/_submit.html.haml
	modified:   app/views/families/show.html.haml
	modified:   app/views/groups/_form_advanced.haml
	modified:   app/views/groups/batch.html.haml
	modified:   app/views/layouts/_footer_links.haml
	modified:   app/views/layouts/_navbar_right.haml
	modified:   app/views/layouts/default.html.haml
	modified:   app/views/layouts/signed_out.html.haml
	modified:   app/views/memberships/_membership.haml
	modified:   app/views/memberships/index.html.haml
	modified:   app/views/messages/_form.html.haml
	modified:   app/views/messages/show.html.haml
	modified:   app/views/people/_details.haml
	modified:   app/views/people/_form.haml
	new file:   app/views/people/_form_visibility.haml
	modified:   app/views/people/email.html.haml
	new file:   app/views/people/import.html.haml
	new file:   app/views/people/import_queue.html.haml
	new file:   app/views/people/import_results.html.haml
	modified:   app/views/prayer_requests/_form.haml
	modified:   app/views/searches/_results.haml
	modified:   app/views/searches/create.html.haml
	modified:   app/views/sessions/new.html.haml
	modified:   app/views/tasks/_form.haml
	modified:   app/views/tasks/_index.haml
	modified:   app/views/tasks/index.haml
	modified:   app/views/tasks/show.haml
	modified:   build/.gitignore
	modified:   build/packer.json
	modified:   build/ubuntu/14.04/provision.sh
	modified:   circle.yml
	modified:   config/deploy.rb
	modified:   config/email.yml.example
	modified:   config/initializers/email.rb
	modified:   config/initializers/geocoder.rb
	modified:   config/locales.yml
	modified:   config/locales/de/groups.yml
	modified:   config/locales/de/messages.yml
	modified:   config/locales/de/nav.yml
	modified:   config/locales/de/notifier.yml
	modified:   config/locales/de/pages.yml
	modified:   config/locales/de/people.yml
	modified:   config/locales/de/prayer_requests.yml
	modified:   config/locales/de/printable_directories.yml
	modified:   config/locales/de/privacies.yml
	modified:   config/locales/de/relationships.yml
	modified:   config/locales/de/search.yml
	modified:   config/locales/de/setup.yml
	modified:   config/locales/de/stream.yml
	modified:   config/locales/de/verses.yml
	modified:   config/locales/en/admin.yml
	modified:   config/locales/en/documents.yml
	modified:   config/locales/en/families.yml
	modified:   config/locales/en/general.yml
	modified:   config/locales/en/groups.yml
	modified:   config/locales/en/nav.yml
	modified:   config/locales/en/people.yml
	modified:   config/locales/en/search.yml
	modified:   config/locales/en/tasks.yml
	modified:   config/locales/es-419/privacies.yml
	modified:   config/locales/es-419/search.yml
	modified:   config/locales/es-419/stream.yml
	modified:   config/locales/es-419/verses.yml
	modified:   config/locales/nl-NL/admin.yml
	modified:   config/locales/nl-NL/attendance.yml
	modified:   config/locales/nl-NL/checkin.yml
	modified:   config/locales/nl-NL/documents.yml
	modified:   config/locales/nl-NL/families.yml
	modified:   config/locales/nl-NL/friends.yml
	modified:   config/locales/nl-NL/general.yml
	modified:   config/locales/nl-NL/groups.yml
	modified:   config/locales/nl-NL/memberships.yml
	modified:   config/locales/nl-NL/messages.yml
	modified:   config/locales/nl-NL/nav.yml
	modified:   config/locales/nl-NL/notifier.yml
	modified:   config/locales/nl-NL/people.yml
	modified:   config/locales/nl-NL/privacies.yml
	modified:   config/locales/nl-NL/relationships.yml
	modified:   config/locales/nl-NL/search.yml
	modified:   config/locales/nl-NL/stream.yml
	modified:   config/locales/nl-NL/verses.yml
	modified:   config/locales/pt/admin.yml
	modified:   config/locales/pt/attendance.yml
	modified:   config/locales/pt/checkin.yml
	modified:   config/locales/pt/documents.yml
	modified:   config/locales/pt/general.yml
	modified:   config/locales/pt/groups.yml
	modified:   config/locales/pt/import.yml
	modified:   config/locales/pt/memberships.yml
	modified:   config/locales/pt/messages.yml
	modified:   config/locales/pt/nav.yml
	modified:   config/locales/pt/people.yml
	modified:   config/locales/pt/prayer_requests.yml
	modified:   config/locales/pt/privacies.yml
	modified:   config/locales/pt/relationships.yml
	modified:   config/locales/pt/reports.yml
	modified:   config/locales/pt/search.yml
	modified:   config/locales/pt/stream.yml
	modified:   config/locales/pt/verses.yml
	modified:   config/locales/ro/albums.yml
	modified:   config/locales/ro/families.yml
	modified:   config/locales/ro/friends.yml
	modified:   config/locales/ro/groups.yml
	modified:   config/locales/ro/import.yml
	modified:   config/locales/ro/memberships.yml
	modified:   config/locales/ro/messages.yml
	modified:   config/locales/ro/nav.yml
	modified:   config/locales/ro/notifier.yml
	modified:   config/locales/ro/people.yml
	modified:   config/locales/ro/photos.yml
	modified:   config/locales/ro/prayer_requests.yml
	modified:   config/locales/ro/privacies.yml
	modified:   config/locales/ro/relationships.yml
	modified:   config/locales/ro/search.yml
	modified:   config/locales/ro/stream.yml
	modified:   config/locales/ro/verses.yml
	modified:   config/routes.rb
	modified:   config/settings.yml
	modified:   db/pages/help/index.html
	modified:   db/pages/help/privacy_policy.html
	modified:   db/schema.rb
	modified:   db/seeds.rb
	modified:   lib/db_tools.rb
	modified:   lib/tasks/export.rake
	modified:   lib/tasks/sites.rake
	modified:   lib/version_info.rb
	new file:   script/docker/bootstrap
	new file:   script/docker/chown_data
	new file:   script/docker/console
	new file:   script/docker/link_dirs
	new file:   script/docker/server
	modified:   script/import_i18n
	modified:   spec/controllers/accounts_controller_spec.rb
	modified:   spec/controllers/documents_controller_spec.rb
	modified:   spec/controllers/memberships_controller_spec.rb
	modified:   spec/controllers/people_controller_spec.rb
	modified:   spec/controllers/sessions_controller_spec.rb
	modified:   spec/controllers/tasks_controller_spec.rb
	modified:   spec/factories/documents.rb
	modified:   spec/factories/families.rb
	modified:   spec/factories/people.rb
	modified:   spec/fixtures/files/people.csv
	modified:   spec/helpers/application_helper_spec.rb
	new file:   spec/jobs/stream_item_group_job_spec.rb
	modified:   spec/models/album_spec.rb
	modified:   spec/models/authorizers/person_authorizer_spec.rb
	modified:   spec/models/document_spec.rb
	new file:   spec/models/email_spec.rb
	modified:   spec/models/family_spec.rb
	modified:   spec/models/group_spec.rb
	modified:   spec/models/person_spec.rb
	modified:   spec/models/picture_spec.rb
	modified:   spec/models/setting_spec.rb
	modified:   spec/models/signup_spec.rb
	modified:   spec/models/task_spec.rb
	modified:   spec/models/verification_spec.rb
	modified:   spec/presenters/stats/attendance_graph_presenter_spec.rb
	modified:   spec/rails_helper.rb
	modified:   spec/requests/groups_spec.rb
	modified:   spec/requests/sign_in_spec.rb
	modified:   spec/spec_helper.rb
	new file:   spec/support/geocoder.rb
	modified:   vendor/assets/javascripts/admin_lte.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Gemfile
	modified:   Gemfile.lock
	modified:   cache/.gitignore
	modified:   log/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config/database.yml~
	config/secrets.yml~
````

Maybe I'm not on the tagged version?  I'm happy to just blow away this dir and try to re-install it?  Do you think that would help?

**Comment by seven1m** [comment]
Ahhh, let's try this:

```
git fetch origin
git reset --hard origin/master
```

...and then start back at step 7.

**Comment by cmivxx** [comment]
ok, I'll try that now.  stay tuned.

**Comment by cmivxx** [comment]
Ok, so now it's a completely different error, but I never got to step 10.  When I run Step 8, specifically `bundle install`, it throws the following (stay tuned after for more info):

````
bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/seven1m/acts_as_taggable_on_steroids.git
Fetching git://github.com/Hermanverschooten/pdf-writer.git
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769" due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769"` in directory /var/lib/gems/2.1.0/bundler/gems/pdf-writer-f57c298a2527 has failed.
If this error persists you could try removing the cache directory '/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769" due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769"` in directory /var/lib/gems/2.1.0/bundler/gems/pdf-writer-f57c298a2527 has failed.
If this error persists you could try removing the cache directory '/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769" due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769"` in directory /var/lib/gems/2.1.0/bundler/gems/pdf-writer-f57c298a2527 has failed.
If this error persists you could try removing the cache directory '/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769'
error: cannot open .git/FETCH_HEAD: Permission denied

Git error: command `git fetch --force --quiet --tags "/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769"` in directory
/var/lib/gems/2.1.0/bundler/gems/pdf-writer-f57c298a2527 has failed.
If this error persists you could try removing the cache directory '/home/chris/.bundler/cache/git/pdf-writer-e1085ee403ccdc31c45292358d47c51ec3d70769'
````

For the record, the .bundler/cache/git folder WAS empty before running it.  After I run it, there IS a "pdf" folder in it.  I tried deleting the folder and rerunning `bundle install` but I get the same issue.

The OTHER part of the error is an issue with `.git/FETCH_HEAD`, which DOES exist, and is FULLY readable by my user.  The source of that file is below:

````
cat FETCH_HEAD
1baea0945b6c698868e9ad45481c85946b3e4d09		branch 'master' of git://github.com/churchio/onebody
9280141f0536bbe07c3c10929547ff91082739b4	not-for-merge	branch '7m/better-docker' of git://github.com/churchio/onebody
062cbb2c8ce798c5b97fb9a9e5e1f0b819a116eb	not-for-merge	branch 'addresses' of git://github.com/churchio/onebody
4dc2438f54101a6b79bf84ecf9176e872ff7b486	not-for-merge	branch 'api' of git://github.com/churchio/onebody
822dd18dbd9abcf9d95f965f8f7dded430eedde5	not-for-merge	branch 'checkin-kiosk' of git://github.com/churchio/onebody
e3adde27fcd3c50cf6a8c3ab4e0bd2ab523752de	not-for-merge	branch 'checkin-print' of git://github.com/churchio/onebody
4e275ad7c2c7aa5e1c0236f50f0290feb455f50a	not-for-merge	branch 'deb' of git://github.com/churchio/onebody
cbce2783b88b86090abb6d53df1f14475b186532	not-for-merge	branch 'family-box' of git://github.com/churchio/onebody
c78ae71e76903e2b1fc14cca7ec27587523422e3	not-for-merge	branch 'fix-reports' of git://github.com/churchio/onebody
0b9d46fbb7c4a1bcac895ea651797861969d0c9b	not-for-merge	branch 'giving' of git://github.com/churchio/onebody
62e99ccc9619261318309276f4f5ffd26bd74309	not-for-merge	branch 'heroku' of git://github.com/churchio/onebody
c5d6ec44ff6b5a0bce81991d024572dcf7c81240	not-for-merge	branch 'prawn' of git://github.com/churchio/onebody
502312dd9af8986af79e5c79bb5ab06c79a1acb6	not-for-merge	branch 'refactor-search' of git://github.com/churchio/onebody
54e4fed7cf938190ec81823e987d8a4ebf1bd855	not-for-merge	branch 'release-3.2.0' of git://github.com/churchio/onebody
5cd5786eab90c100c5b6261128e1adc9658e7921	not-for-merge	branch 'reporting' of git://github.com/churchio/onebody
````

So, now it's starting to look like my copy of the repo may be munged, though I had previously reset it...  I'm lost.  Got any other ideas?  I'm likely off for the night though, so tomorrow is another day.

Thanks for the help.

**Comment by seven1m** [comment]
Strange! OK, at this point, I'd definitely delete the onebody directory and start back at step 4.

You can skip 6 though, since your database should already exist.
